<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261007065914 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cheque (id UUID NOT NULL, reference_fictive VARCHAR(40) NOT NULL, montant_en_centimes BIGINT NOT NULL, manquant_en_centimes BIGINT DEFAULT NULL, provision_totalement_absente BOOLEAN NOT NULL, date_emission_portee_sur_le_cheque DATE NOT NULL, lieu_emission VARCHAR(16) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE dossier (id UUID NOT NULL, version INT DEFAULT 1 NOT NULL, reference VARCHAR(32) NOT NULL, etat VARCHAR(48) NOT NULL, cas_article316 VARCHAR(40) NOT NULL, date_incident_de_paiement DATE DEFAULT NULL, date_injonction_bancaire DATE DEFAULT NULL, date_plainte DATE DEFAULT NULL, date_ecedar DATE DEFAULT NULL, duree_delai_initial_en_jours SMALLINT NOT NULL, quota_prolongations_de_ce_logiciel SMALLINT NOT NULL, disponibilite_beneficiaire VARCHAR(24) NOT NULL, lien_familial_tireur_beneficiaire VARCHAR(32) NOT NULL, date_dissolution_du_mariage DATE DEFAULT NULL, paiement_integral_effectue BOOLEAN NOT NULL, amende_deux_pour_cent_payee BOOLEAN NOT NULL, amende_article316_payee BOOLEAN NOT NULL, consignation_au_greffe_effectuee BOOLEAN NOT NULL, mesures_de_controle_judiciaire JSON NOT NULL, cheque_id UUID NOT NULL, tireur_id UUID NOT NULL, beneficiaire_id UUID NOT NULL, interdiction_bancaire_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3D48E037AEA34913 ON dossier (reference)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3D48E0373DD3DB4B ON dossier (cheque_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3D48E037944DDB6E ON dossier (interdiction_bancaire_id)');
        $this->addSql('CREATE INDEX idx_dossier_etat ON dossier (etat)');
        $this->addSql('CREATE INDEX idx_dossier_date_ecedar ON dossier (date_ecedar)');
        $this->addSql('CREATE INDEX IDX_3D48E037CE287986 ON dossier (tireur_id)');
        $this->addSql('CREATE INDEX IDX_3D48E0375AF81F68 ON dossier (beneficiaire_id)');
        $this->addSql('CREATE TABLE evenement_dossier (id UUID NOT NULL, type_piece VARCHAR(48) NOT NULL, survenu_le DATE NOT NULL, reference_piece_fictive VARCHAR(64) NOT NULL, dossier_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_evenement_type ON evenement_dossier (type_piece)');
        $this->addSql('CREATE INDEX IDX_3E4DF7EB611C0C56 ON evenement_dossier (dossier_id)');
        $this->addSql('CREATE TABLE interdiction_bancaire (id UUID NOT NULL, version INT DEFAULT 1 NOT NULL, etat VARCHAR(16) NOT NULL, date_incident_de_paiement DATE NOT NULL, echeance_du_delai_de_presentation DATE NOT NULL, rang_de_linjonction SMALLINT NOT NULL, paiement_ou_provision_constituee BOOLEAN NOT NULL, date_paiement_ou_provision DATE DEFAULT NULL, penalite_article314_payee BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE partie (id UUID NOT NULL, nom_fictif VARCHAR(160) NOT NULL, courriel_de_contact VARCHAR(180) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE prolongation (id UUID NOT NULL, demandee_le DATE NOT NULL, duree_en_jours SMALLINT NOT NULL, date_decision_du_parquet DATE DEFAULT NULL, reference_decision_du_parquet_fictive VARCHAR(64) DEFAULT NULL, date_accord_du_beneficiaire DATE DEFAULT NULL, reference_accord_du_beneficiaire_fictive VARCHAR(64) DEFAULT NULL, accordee_le DATE DEFAULT NULL, dossier_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EBBF9907611C0C56 ON prolongation (dossier_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE dossier ADD CONSTRAINT FK_3D48E0373DD3DB4B FOREIGN KEY (cheque_id) REFERENCES cheque (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dossier ADD CONSTRAINT FK_3D48E037CE287986 FOREIGN KEY (tireur_id) REFERENCES partie (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dossier ADD CONSTRAINT FK_3D48E0375AF81F68 FOREIGN KEY (beneficiaire_id) REFERENCES partie (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dossier ADD CONSTRAINT FK_3D48E037944DDB6E FOREIGN KEY (interdiction_bancaire_id) REFERENCES interdiction_bancaire (id)');
        $this->addSql('ALTER TABLE evenement_dossier ADD CONSTRAINT FK_3E4DF7EB611C0C56 FOREIGN KEY (dossier_id) REFERENCES dossier (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prolongation ADD CONSTRAINT FK_EBBF9907611C0C56 FOREIGN KEY (dossier_id) REFERENCES dossier (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dossier DROP CONSTRAINT FK_3D48E0373DD3DB4B');
        $this->addSql('ALTER TABLE dossier DROP CONSTRAINT FK_3D48E037CE287986');
        $this->addSql('ALTER TABLE dossier DROP CONSTRAINT FK_3D48E0375AF81F68');
        $this->addSql('ALTER TABLE dossier DROP CONSTRAINT FK_3D48E037944DDB6E');
        $this->addSql('ALTER TABLE evenement_dossier DROP CONSTRAINT FK_3E4DF7EB611C0C56');
        $this->addSql('ALTER TABLE prolongation DROP CONSTRAINT FK_EBBF9907611C0C56');
        $this->addSql('DROP TABLE cheque');
        $this->addSql('DROP TABLE dossier');
        $this->addSql('DROP TABLE evenement_dossier');
        $this->addSql('DROP TABLE interdiction_bancaire');
        $this->addSql('DROP TABLE partie');
        $this->addSql('DROP TABLE prolongation');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
